#plot 'data.dat' with lines
#plot 'data.dat' with linespoints
#plot 'data.dat' with dots
#plot 'data.dat' with boxes
#plot 'data.dat' with boxerrorbars
#plot 'data.dat' with boxxyerrorbars
#plot 'data.dat' with errorbars
#plot 'data.dat' with impulse
plot 'data.dat' with step